version: 2
jobs:
  build:
    working_directory: ~/site-devfest
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - restore_cache:
          keys:
            - theme-deps-{{ checksum "themes/devfest-theme-hugo/package.json" }}
            - theme-deps-
      - run: cd themes/devfest-theme-hugo && npm install && npm run build
      - save_cache:
          paths: themes/devfest-theme-hugo/node_modules
          key: theme-deps-{{ checksum "themes/devfest-theme-hugo/package.json" }}
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - persist_to_workspace:
          root: ./
          paths:
            - public

    deploy:
      working_directory: ~/site-devfest
      docker:
        - image: circleci/node:10.15.3
      steps:
        - checkout
        - restore_cache:
            keys:
              - main-deps-{{ checksum "package.json" }}
              - main-deps-
        - run: npm i
        - save_cache:
            paths: node_modules
            key: main-deps-{{ checksum "package.json" }}
        - attach_workspace:
            at: ~/site-devfest
        - run: npm run deploy:ci

workflows:
  version: 2
  build-deploy-master:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
