version: 2.1

orbs:
  hugo: circleci/hugo@0.3.1

workflows:
  main:
    jobs:
      - hugo/build:
          version: '0.55.6'
      - deploy:
          requires:
            - hugo/build
          filters:
            branches:
              only: master

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - main-deps-{{ checksum "package.json" }}
            - main-deps-
      - run: npm install
      - save_cache:
          paths: node_modules
          key: main-deps-{{ checksum "package.json" }}
      - attach_workspace:
          at: .
      - run: npm run deploy:ci
