version: 2
jobs:
  build-theme:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - restore_cache:
          keys:
            - theme-deps-{{ checksum "themes/devfest-theme-hugo/package.json" }}
            - theme-deps-
      - run: cd themes/devfest-theme-hugo && npm install && npm run build
      - save_cache:
          paths: themes/devfest-theme-hugo/node_modules
          key: theme-deps-{{ checksum "themes/devfest-theme-hugo/package.json" }}
      - persist_to_workspace:
          root: themes/devfest-theme-hugo
          paths:
            - static

  build-site:
    docker:
      - image: circleci/hugo:latest
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - attach_workspace:
          at: themes/devfest-theme-hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - persist_to_workspace:
          root: .
          paths:
            - public

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - main-deps-{{ checksum "package.json" }}
            - main-deps-
      - run: npm install
      - save_cache:
          paths: node_modules
          key: main-deps-{{ checksum "package.json" }}
      - attach_workspace:
          at: .
      - run: npm run deploy:ci

workflows:
  version: 2
  build-deploy-master:
    jobs:
      - build-theme
      - build-site
      - deploy:
          requires:
            - build-theme
            - build-site
          filters:
            branches:
              only: master
